
+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
${CVA6_ROOT}/.bender/git/checkouts/common_verification-fd5a4c811d618157/src/clk_rst_gen.sv
${CVA6_ROOT}/.bender/git/checkouts/common_verification-fd5a4c811d618157/src/sim_timeout.sv
${CVA6_ROOT}/.bender/git/checkouts/common_verification-fd5a4c811d618157/src/stream_watchdog.sv
${CVA6_ROOT}/.bender/git/checkouts/common_verification-fd5a4c811d618157/src/signal_highlighter.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
${CVA6_ROOT}/.bender/git/checkouts/tech_cells_generic-cc24c124b7267269/src/rtl/tc_sram.sv
${CVA6_ROOT}/.bender/git/checkouts/tech_cells_generic-cc24c124b7267269/src/rtl/tc_sram_impl.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
${CVA6_ROOT}/.bender/git/checkouts/tech_cells_generic-cc24c124b7267269/src/rtl/tc_clk.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
${CVA6_ROOT}/.bender/git/checkouts/tech_cells_generic-cc24c124b7267269/src/rtl/tc_sync.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
${CVA6_ROOT}/.bender/git/checkouts/tech_cells_generic-cc24c124b7267269/src/deprecated/pulp_clock_gating_async.sv
${CVA6_ROOT}/.bender/git/checkouts/tech_cells_generic-cc24c124b7267269/src/deprecated/cluster_clk_cells.sv
${CVA6_ROOT}/.bender/git/checkouts/tech_cells_generic-cc24c124b7267269/src/deprecated/pulp_clk_cells.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/binary_to_gray.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cb_filter_pkg.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cc_onehot.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cdc_reset_ctrlr_pkg.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cf_math_pkg.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/clk_int_div.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/credit_counter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/delta_counter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/ecc_pkg.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/edge_propagator_tx.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/exp_backoff.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/fifo_v3.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/gray_to_binary.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/heaviside.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/isochronous_4phase_handshake.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/isochronous_spill_register.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/lfsr.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/lfsr_16bit.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/lfsr_8bit.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/lossy_valid_to_stream.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/mv_filter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/onehot_to_bin.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/plru_tree.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/passthrough_stream_fifo.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/popcount.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/ring_buffer.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/rr_arb_tree.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/rstgen_bypass.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/serial_deglitch.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/shift_reg.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/shift_reg_gated.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/spill_register_flushable.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_demux.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_filter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_fork.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_intf.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_join_dynamic.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_mux.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_throttle.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/sub_per_hash.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/sync.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/sync_wedge.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/unread.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/read.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/addr_decode_dync.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/boxcar.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cdc_2phase.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cdc_4phase.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/clk_int_div_static.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/trip_counter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/addr_decode.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/addr_decode_napot.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/multiaddr_decode.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cb_filter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cdc_fifo_2phase.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/clk_mux_glitch_free.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/counter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/ecc_decode.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/ecc_encode.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/edge_detect.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/lzc.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/max_counter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/rstgen.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/spill_register.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_delay.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_fifo.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_fork_dynamic.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_join.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cdc_reset_ctrlr.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cdc_fifo_gray.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/fall_through_register.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/id_queue.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_to_mem.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_arbiter_flushable.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_fifo_optimal_wrap.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_register.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_xbar.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cdc_fifo_gray_clearable.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cdc_2phase_clearable.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/mem_to_banks_detailed.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_arbiter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_omega_net.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/mem_to_banks.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/clock_divider_counter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/clk_div.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/find_first_one.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/generic_LFSR_8bit.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/generic_fifo.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/prioarbiter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/pulp_sync.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/pulp_sync_wedge.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/rrarbiter.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/clock_divider.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/fifo_v2.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/deprecated/fifo_v1.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/edge_propagator_ack.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/edge_propagator.sv
${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/edge_propagator_rx.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
${CVA6_ROOT}/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/defs_div_sqrt_mvp.sv
${CVA6_ROOT}/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/iteration_div_sqrt_mvp.sv
${CVA6_ROOT}/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/control_mvp.sv
${CVA6_ROOT}/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/norm_div_sqrt_mvp.sv
${CVA6_ROOT}/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/preprocess_mvp.sv
${CVA6_ROOT}/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/nrbd_nrsc_mvp.sv
${CVA6_ROOT}/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/div_sqrt_top_mvp.sv
${CVA6_ROOT}/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/div_sqrt_mvp_wrapper.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/include
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_pkg.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_intf.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_atop_filter.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_burst_splitter.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_cdc_dst.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_cdc_src.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_cut.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_delayer.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_demux.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_dw_downsizer.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_dw_upsizer.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_id_remap.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_id_prepend.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_isolate.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_join.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_lite_demux.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_lite_join.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_lite_mailbox.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_lite_mux.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_lite_regs.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_lite_to_apb.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_lite_to_axi.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_modify_address.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_mux.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_serializer.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_cdc.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_err_slv.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_dw_converter.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_id_serialize.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_multicut.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_to_axi_lite.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_iw_converter.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_lite_xbar.sv
${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_xbar.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_pkg.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_cast_multi.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_classifier.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_divsqrt_th_32.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_divsqrt_th_64_multi.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_divsqrt_multi.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/cvw/fma/fmalza.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_fma.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_fma_multi.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_noncomp.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_opgroup_block.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_opgroup_fmt_slice.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_opgroup_multifmt_slice.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_rounding.sv
${CVA6_ROOT}/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_top.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/include
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc
+incdir+${CVA6_ROOT}/core/include
${CVA6_ROOT}/core/include/config_pkg.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/include
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc
+incdir+${CVA6_ROOT}/core/include
${CVA6_ROOT}/core/include/cv32a6_imac_sv32_config_pkg.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/include
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc
+incdir+${CVA6_ROOT}/core/include
${CVA6_ROOT}/core/include/riscv_pkg.sv
${CVA6_ROOT}/core/include/ariane_pkg.sv
${CVA6_ROOT}/core/include/build_config_pkg.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/include
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc
+incdir+${CVA6_ROOT}/core/include
${CVA6_ROOT}/core/cva6_accel_first_pass_decoder_stub.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/include
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc
+incdir+${CVA6_ROOT}/core/include
${CVA6_ROOT}/core/cva6_mmu/cva6_tlb.sv
${CVA6_ROOT}/core/cva6_mmu/cva6_shared_tlb.sv
${CVA6_ROOT}/core/cva6_mmu/cva6_mmu.sv
${CVA6_ROOT}/core/cva6_mmu/cva6_ptw.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/include
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc
+incdir+${CVA6_ROOT}/core/include
${CVA6_ROOT}/core/include/dummy_l15_pkg.sv
${CVA6_ROOT}/core/include/wt_cache_pkg.sv
${CVA6_ROOT}/core/include/std_cache_pkg.sv
${CVA6_ROOT}/core/include/aes_pkg.sv
${CVA6_ROOT}/core/cvxif_example/include/cvxif_instr_pkg.sv
${CVA6_ROOT}/core/cvxif_fu.sv
${CVA6_ROOT}/core/cvxif_issue_register_commit_if_driver.sv
${CVA6_ROOT}/core/cvxif_compressed_if_driver.sv
${CVA6_ROOT}/core/cvxif_example/cvxif_example_coprocessor.sv
${CVA6_ROOT}/core/cvxif_example/instr_decoder.sv
${CVA6_ROOT}/core/cva6_rvfi_probes.sv
${CVA6_ROOT}/core/cva6_fifo_v3.sv
${CVA6_ROOT}/core/cva6.sv
${CVA6_ROOT}/core/aes.sv
${CVA6_ROOT}/core/alu.sv
${CVA6_ROOT}/core/alu_wrapper.sv
${CVA6_ROOT}/core/fpu_wrap.sv
${CVA6_ROOT}/core/branch_unit.sv
${CVA6_ROOT}/core/compressed_decoder.sv
${CVA6_ROOT}/core/controller.sv
${CVA6_ROOT}/core/csr_buffer.sv
${CVA6_ROOT}/core/csr_regfile.sv
${CVA6_ROOT}/core/decoder.sv
${CVA6_ROOT}/core/ex_stage.sv
${CVA6_ROOT}/core/acc_dispatcher.sv
${CVA6_ROOT}/core/instr_realign.sv
${CVA6_ROOT}/core/id_stage.sv
${CVA6_ROOT}/core/issue_read_operands.sv
${CVA6_ROOT}/core/issue_stage.sv
${CVA6_ROOT}/core/load_unit.sv
${CVA6_ROOT}/core/load_store_unit.sv
${CVA6_ROOT}/core/lsu_bypass.sv
${CVA6_ROOT}/core/mult.sv
${CVA6_ROOT}/core/multiplier.sv
${CVA6_ROOT}/core/serdiv.sv
${CVA6_ROOT}/core/perf_counters.sv
${CVA6_ROOT}/core/ariane_regfile_ff.sv
${CVA6_ROOT}/core/ariane_regfile_fpga.sv
${CVA6_ROOT}/core/scoreboard.sv
${CVA6_ROOT}/core/raw_checker.sv
${CVA6_ROOT}/core/store_buffer.sv
${CVA6_ROOT}/core/amo_buffer.sv
${CVA6_ROOT}/core/store_unit.sv
${CVA6_ROOT}/core/commit_stage.sv
${CVA6_ROOT}/core/axi_shim.sv
${CVA6_ROOT}/core/frontend/btb.sv
${CVA6_ROOT}/core/frontend/bht.sv
${CVA6_ROOT}/core/frontend/bht2lvl.sv
${CVA6_ROOT}/core/frontend/ras.sv
${CVA6_ROOT}/core/frontend/instr_scan.sv
${CVA6_ROOT}/core/frontend/instr_queue.sv
${CVA6_ROOT}/core/frontend/frontend.sv
${CVA6_ROOT}/core/cache_subsystem/wt_dcache_ctrl.sv
${CVA6_ROOT}/core/cache_subsystem/wt_dcache_mem.sv
${CVA6_ROOT}/core/cache_subsystem/wt_dcache_missunit.sv
${CVA6_ROOT}/core/cache_subsystem/wt_dcache_wbuffer.sv
${CVA6_ROOT}/core/cache_subsystem/wt_dcache.sv
${CVA6_ROOT}/core/cache_subsystem/wt_cache_subsystem.sv
${CVA6_ROOT}/core/cache_subsystem/wt_axi_adapter.sv
${CVA6_ROOT}/core/cache_subsystem/cva6_icache.sv
${CVA6_ROOT}/core/cache_subsystem/tag_cmp.sv
${CVA6_ROOT}/core/cache_subsystem/cva6_icache_axi_wrapper.sv
${CVA6_ROOT}/core/cache_subsystem/axi_adapter.sv
${CVA6_ROOT}/core/cache_subsystem/miss_handler.sv
${CVA6_ROOT}/core/cache_subsystem/cache_ctrl.sv
${CVA6_ROOT}/core/cache_subsystem/std_nbdcache.sv
${CVA6_ROOT}/core/cache_subsystem/std_cache_subsystem.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_lfsr.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg_initialized.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_decoder.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_1hot_to_binary.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_bin_encoder.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_resize.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_plru.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_random.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_sel.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_flush.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cbuf.sv
${CVA6_ROOT}/core/cache_subsystem/cva6_hpdcache_if_adapter.sv
${CVA6_ROOT}/core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv
${CVA6_ROOT}/core/cache_subsystem/cva6_hpdcache_subsystem.sv
${CVA6_ROOT}/core/cache_subsystem/cva6_hpdcache_wrapper.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_pkg.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_36_29_dec.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_36_29_enc.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_39_32_dec.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_39_32_enc.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_55_48_dec.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_55_48_enc.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_72_64_dec.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_72_64_enc.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_1rw.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_ecc_1rw.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wbyteenable_1rw.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wbyteenable_ecc_1rw.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wmask_1rw.sv
${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wmask_ecc_1rw.sv
${CVA6_ROOT}/core/pmp/src/pmp.sv
${CVA6_ROOT}/core/pmp/src/pmp_entry.sv
${CVA6_ROOT}/core/pmp/src/pmp_data_if.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/include
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
+incdir+${CVA6_ROOT}/common/local/util
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc
+incdir+${CVA6_ROOT}/core/include
${CVA6_ROOT}/common/local/util/sram.sv

+define+TARGET_CV32A6_IMAC_SV32
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+${CVA6_ROOT}/.bender/git/checkouts/axi-f14341c32cf56c49/include
+incdir+${CVA6_ROOT}/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
+incdir+${CVA6_ROOT}/common/local/util
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/include
+incdir+${CVA6_ROOT}/core/cache_subsystem/hpdcache/rtl/src/utils/ecc
+incdir+${CVA6_ROOT}/core/include
${CVA6_ROOT}/common/local/util/tc_sram_wrapper.sv
${CVA6_ROOT}/common/local/util/sram_cache.sv
${CVA6_ROOT}/common/local/util/tc_sram_wrapper_cache_techno.sv

